name: Python Application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11, 3.12]
        poetry-version: [1.8.2]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instalar Poetry ${{ matrix.poetry-version }}
        run: |
          python -m pip install --upgrade pip
          pip install poetry==${{ matrix.poetry-version }}

      - name: Instalar dependências
        run: poetry install

      - name: Rodar testes com Django
        run: poetry run python manage.py test
        
