name: Python Application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11, 3.12] # Atualizado para versões modernas
        poetry-version: [1.8.2]      # Última versão estável em abril/2025

    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instalar Poetry ${{ matrix.poetry-version }}
        run: |
          python -m pip install --upgrade pip
          pip install poetry==${{ matrix.poetry-version }}
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Verificar ajuda do Poetry
        run: poetry --help

      - name: Instalar dependências com Poetry
        run: poetry install

      - name: Executar testes com Django
        run: poetry run python manage.py test
