name: Python Pull Request Workflow

on: [pull_request]

jobs:
  qa:
    name: Quality Check
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.0-alpine
        env:
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
          POSTGRES_DB: bookstore_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: bookstore_db
      DATABASE_URL: postgres://dev:dev@localhost:5432/bookstore_db

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências com Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Migrar banco e rodar testes com Django
        run: |
          python manage.py migrate
          python manage.py test

      - name: Checagem com wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.16.0
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

